### ISSUE TITLE
not reproducing fence diagram plot section ordering in pystrat-tutorial.ipynb

### ISSUE THREAD

**Issue by Swanson-Hysell** [yuempark/pystrat#15]
When I run the `pystrat-tutorial.ipynb` notebook the fence diagram that I see looks like:
<img width="559" alt="Screenshot 2024-06-05 at 3 10 17 PM" src="https://github.com/yuempark/pystrat/assets/4332322/5ea3e0fd-a519-419d-baa9-eda179293cae">

rather than the version in master:
<img width="570" alt="Screenshot 2024-06-05 at 3 07 05 PM" src="https://github.com/yuempark/pystrat/assets/4332322/a6b889d1-b594-4e0f-bdc2-2bb64ee57ca9">

The issue appears to be a difference in the order of the sections. I can fix the issue by updating the datum to be defined as:

```
datum = np.array([99, 338.9, 22.9, 79.5]).reshape(-1, 1) # datum is a 1D array
```

and the coordinates parameter within fence to be:

```
fence = pystrat.Fence(sections, 
                      coordinates=np.array([3, 1, 2, 4]),
                      datums=datum)
```

These values differ from the order that is currently in the master which are:

<img width="811" alt="Screenshot 2024-06-05 at 3 19 52 PM" src="https://github.com/yuempark/pystrat/assets/4332322/6c69dd94-3c24-449b-a0c5-ae6a50315e37">

**Comment by Swanson-Hysell** [comment]
Could you have a look at this @sarttiso ? I can make the change in the `pystrat-tutorial.ipynb` notebook that fixed the issue for me, but I want to make sure there aren't deeper issues with the sections being read in with different orders at different times. Perhaps we want to define a dictionary or another data structure that can carry along the section name to make it more stable if that is the case.

**Comment by sarttiso** [comment]
Ah, it's probably some error with how `glob.glob('T*.csv')` is ordering the files, may be an OS thing (I'm on Windows). I think your dictionary suggestion is the easiest, so I'll just define a dictionary that specifies the section order for `section_files` and `sections`, and that should ensure that they're always read in the appropriate order.
